### ISSUE TITLE
Unable to run in docker

### ISSUE THREAD

**Issue by aap01** [JAIJANYANI/Automated-Resume-Screening-System#50]
When I run this command
```bash
docker run -it -p 5000:5000 arss:latest
```
I see the following output in the terminal
```bash
Traceback (most recent call last):
  File "app.py", line 49, in <module>
    from flask import (Flask,session, g, json, Blueprint,flash, jsonify, redirect, render_template, request,
  File "/usr/local/lib/python3.7/site-packages/flask/__init__.py", line 14, in <module>
    from jinja2 import escape
ImportError: cannot import name 'escape' from 'jinja2' (/usr/local/lib/python3.7/site-packages/jinja2/__init__.py)
```

**Comment by yusufdemyr** [comment]
You should update requirements file. Like this:
```
textract==1.6.3
requests==2.31.0
Flask==2.2.2
gensim==3.8.0
sklearn==0.0
PyPDF2==1.27.9
autocorrect==0.4.4
nltk==3.6.6
contractions==0.0.21
textsearch==0.0.17
inflect==2.1.0
numpy==1.21.6
pdfminer.six==20181108
```
